### ISSUE TITLE
Kaspersky declare Nuxeo Drive as Trojan

### ISSUE THREAD

**Issue by villemar** [nuxeo/nuxeo-drive#1180]
Kaspersky Endpoint Security for Windows (11.1.0 > 11.0.0.6499) on Windows 10

**Comment by BoboTiG** [comment]
Hello,

We are aware of such false positive. From time to time, 1 or 2 antivirus saw the compiled binaries as trojans or virus. This will be fixed in a near future update of the antivirus.

For example, another past false positive: https://www.virustotal.com/gui/file/4cfdcc709f6338dd90fc4b65df002943937f6cddd5da15fabc5135dd3bbefd3b/detection

Finally, there is nothing we can do, this is how antivrus works. We are using PyInstaller to freeze the app and this is what antivirus found as trojan: https://github.com/pyinstaller/pyinstaller/issues/4062.

I am closing the issue as won't fix and hope Kaspersky will remove that false positive from their definitions.

Regards,
