### ISSUE TITLE
ndrive not working on Fedora 20

### ISSUE THREAD

**Issue by geoffdigital** [nuxeo/nuxeo-drive#16]
Hello,

For some reason I get the following when I run ndrive on Fedora 20:

Traceback (most recent call last):
  File "/usr/bin/ndrive", line 5, in <module>
    from nxdrive.commandline import main
ImportError: No module named commandline

I made sure that I have all the requirements and I also installed https://pypi.python.org/pypi/commandline/0.1.4dev

Any ideas?

Geoff

**Comment by ataillefer** [comment]
Hi,

Sorry about this, it is due to some recent commits related to a global refactoring that has just started on the master branch.

For a while the master branch will not be considered as stable as work is in progress on this branch. Please use the 1.4 branch as a reference. This is the maintenance branch for the latest released version of Nuxeo Drive.

To be sure you are working on a clean base, please first uninstall the previous version of nuxeo-drive:

    sudo pip uninstall nuxeo-drive

Then, as indicated in https://github.com/nuxeo/nuxeo-drive/tree/1.4#ubuntudebian-and-other-linux-variants-client, just run:

    sudo pip install -U -r https://raw.github.com/nuxeo/nuxeo-drive/1.4/requirements.txt
    sudo pip install -U git+https://github.com/nuxeo/nuxeo-drive.git@1.4

PS: The `commandline` module is internal to nuxeo-drive, nothing to do with https://pypi.python.org/pypi/commandline/

Hope this helps!
