### ISSUE TITLE
Cannot install version 3.1.0 via pip

### ISSUE THREAD

**Issue by marcomilanesio** [nuxeo/nuxeo-drive#543]
$ DRIVE_VERSION=3.1.0
    $ sudo pip install -r https://raw.github.com/nuxeo/nuxeo-drive/$DRIVE_VERSION/requirements.txt

The requirements installation is ok.

    $ sudo pip install git+https://github.com/nuxeo/nuxeo-drive.git@$DRIVE_VERSION
    Collecting git+https://github.com/nuxeo/nuxeo-drive.git@release-3.1.0
    Cloning https://github.com/nuxeo/nuxeo-drive.git (to release-3.1.0) to /tmp/pip-Npm3Iy-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
    File "<string>", line 1, in <module>
    IOError: [Errno 2] No such file or directory: '/tmp/pip-Npm3Iy-build/setup.py'
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-Npm3Iy-build/

OS: Fedora 25.

Thanks

**Comment by BoboTiG** [comment]
Hello,

Nuxeo Drive is no more installable from PyPi since 3.1.0.

As it is not a module but a complete software, it was decided for maintenance and deployment reasons to drop its availability from PyPi. With the incoming version, the installation of Drive will be easier as we removed old depencies like Qt4. And we will quickly provide an official way to install it on GNU/Linux (see [NXDRIVE-1280](https://jira.nuxeo.com/browse/NXDRIVE-1280) for a status but keep in mind this is not clearly decided how we will proceed and we are still in the R&D phase).

Thank you for your comprehension.
