### ISSUE TITLE
DLL load failed on Windows XP

### ISSUE THREAD

**Issue by doudz** [nuxeo/nuxeo-drive#55]
After a fresh install of nuxeo-drive.msi I got the following error on Windows XP SP3
ImportError :  DLL load failed
(see attached picture for more information)
![ndrive_crash](https://cloud.githubusercontent.com/assets/1262548/10541951/e5378052-7414-11e5-84be-1cf044849e26.png)

This doesn't occurred on Windows 7

**Comment by ataillefer** [comment]
Yes, we don't support Windows XP anymore...
You'll need to upgrade to at least Windows Seven.

Sorry for the inconvenience.

**Comment by doudz** [comment]
Oh bad news... what is the missing DLL ?

**Comment by doudz** [comment]
Well, investigating I make it works by :
- removing psutil from library.zip
- adding the latest psutil (from my python27 install) in the ndrive folder

So it works, the compatibility problem is just a problem of psutil version I think

**Comment by doudz** [comment]
In fact, removing psutil in library.zip is not needed, just adding the latest psutil in the nuxeo-drive-2.0.911.win32 folder is enough to make it works

**Comment by ataillefer** [comment]
Yes indeed, this is probably because is we are building the Nuxeo Drive MSI under WIndows Server 2012 with Python 2.7.10.

Ideally I think we could have a "universal" build using virtualenv.

Note that you can always build the MSI from sources following https://github.com/nuxeo/nuxeo-drive/blob/master/DEVELOPERS.md.
